<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="http://practice.com/OCT2023Pratice/BillingSystem/BillingSystemBPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://xmlns.oracle.com/OCT2023Pratice/OrderProcessingSystem/OPSBPEL" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/OPSBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OrderRequest" namespace="http://xmlns.oracle.com/OCT2023Pratice/OrderProcessingSystem/OPSBPEL"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://LAPTOP-GVBVNCLO:7101/soa-infra/services/OCT2023/BillingSystem!1.0/WSDLs/BillingSystemBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="BsRequst" namespace="http://practice.com/OCT2023Pratice/BillingSystem/BillingSystemBPEL"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [SUN OCT 15 15:41:49 IST 2023].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:BsRequst>
         <tns:OraderId>
            <xsl:value-of select="/ns0:OrderRequest/ns0:OrderId"/>
         </tns:OraderId>
         <xsl:for-each select="/ns0:OrderRequest/ns0:LineIteam">
            <tns:iteaminfo>
               <tns:iteamName>
                  <xsl:value-of select="ns0:ProduectName"/>
               </tns:iteamName>
               <tns:iteamCost>
                  <xsl:value-of select="ns0:ProduectCust"/>
               </tns:iteamCost>
            </tns:iteaminfo>
         </xsl:for-each>
      </tns:BsRequst>
   </xsl:template>
</xsl:stylesheet>
